apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secret-sealed.yaml
images:
- name: iflwx/flask-demo
  newTag: 91d4e3d987de9b9051251338c1d586814384a6cc
